### ISSUE TITLE
Rework welcome home greetings

### ISSUE THREAD

**Issue by ntalekt** [ntalekt/homeassistant#17]
How to have same greeting if two people arrive home at same time?

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/automation/Speech/announcements.yaml

**Comment by ntalekt** [comment]
Thanks @CCOSTAN for the examples!! They worked great.

**Comment by CCOSTAN** [comment]
Awesome! If you come up with good new sayings, be sure to PR them back into my Repo. :)
