### ISSUE TITLE
GUI interface

### ISSUE THREAD

**Issue by Vikinge** [ntalekt/homeassistant#43]
Are the included yaml files used to create the actual web interface?  Or just all the entities and objects used?  Everything I read shows a ui-lovelace.yaml or configure UI to create the actual interface, is this true?   
If you did use the ui-lovelace.yaml, I can understand why you did not want to include that, I just wanted to make sure I understand that I need to build one to create all the cards similar to what you've created.

**Comment by ntalekt** [comment]
Nope, they are just the configuration files for now. I've been working on porting everything to Lovelace using the UI method which doesn't split the UI elements in a ui-lovelace.yaml. The default Lovelace UI configs are stored in `.homeassistant/.storage`.

I'm thinking after I fully port everything over I'll split it out to a separate UI yaml so it can be shared. There is a lot of clean up of the customize and groups yamls that just aren't needed in the new Lovelace UI.
